version: "2.3"

services:

  uoc-cloud:
    build:
      context: .
    volumes: 
      - ./cfg/:/cfg/
      - ./src/:/src/
    environment:
      - URL_UOC=django
      - PORT_UOC=8000
      - HORAS_VISUALIZACIONES=1
    restart: unless-stopped
    command: sh -c "python3 /src/main.py"

 
  postgres:
    image: postgres
    logging:
      driver: none
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: siali
      POSTGRES_DB: element
    volumes:
      - osasys_postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -d element"]
        interval: 10s
        timeout: 10s
        retries: 30
    restart: unless-stopped
  
  django:
    image: siali/acciona-oasys-interface:1
    ports:
      - 80:8000
    volumes: 
      - ./files/imgs:/app/media/
      - ~/.git-credentials:/etc/git-credentials
    environment:
      - INSTALL_MODULES=true
      - SAMPLE=false
      - LOG_LEVEL=error #option: debug ,info, warning, error and critical (django and gunicorn)
      - RUN_MODE=0 # 0 (runserver), 1 (gunicorn)
    depends_on: 
      postgres:
        condition: service_healthy
    command: sh -c "./run.sh"
    restart: unless-stopped


volumes:
    osasys_postgres:
